set -g default-shell /usr/bin/zsh
set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0
setw -g mode-keys vi

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# clone this first:
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Status Bar
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left

set -g status-style "bg=#1F1F28,fg=#DCD7BA"

set -g window-status-current-style "bg=#2D4F67,fg=#DCD7BA,bold"
set -g window-status-style "bg=#1F1F28,fg=#727169"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-separator ""

set -g pane-border-style "fg=#54546D"
set -g pane-active-border-style "fg=#7E9CD8"

set -g status-left-length 40
set -g status-left "#[bg=#7E9CD8,fg=#1F1F28,bold] #S #[bg=#1F1F28,fg=#7E9CD8]"

set -g status-right-length 100
set -g status-right "#[fg=#727169]%Y-%m-%d #[fg=#DCD7BA]%H:%M "

set -g message-style "bg=#2D4F67,fg=#DCD7BA"
set -g mode-style "bg=#54546D,fg=#DCD7BA"

set -g pane-border-status off
set -g pane-border-lines single

set -g display-panes-time 1500
set -g display-time 1500

set -g monitor-activity on
set -g visual-activity off

set -sg escape-time 10
set -g focus-events on

#plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

