# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(222021)
$foreground = rgb(9F999B)
$color0 = rgb(222021)
$color1 = rgb(936C7A)
$color2 = rgb(CCA133)
$color3 = rgb(FFCC4D)
$color4 = rgb(9C818B)
$color5 = rgb(CCA133)
$color6 = rgb(D27998)
$color7 = rgb(9F999B)
$color8 = rgb(635F60)
$color9 = rgb(DDAF3C)
$color10 = rgb(2F2D2E)
$color11 = rgb(565254)
$color12 = rgb(706B6D)
$color13 = rgb(F0A8C1)
$color14 = rgb(C39622)
$color15 = rgb(FFEBF2)
