# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this

input {
  kb_layout = gb, pk
  kb_variant = extd
  kb_model =
  kb_options =
  kb_rules =
  repeat_rate = 50
  repeat_delay = 300
  sensitivity = 0 #mouse sensitivity
  #accel_profile =     # flat or adaptive or blank or EMPTY means libinput’s default mode
  numlock_by_default = true
  left_handed = false
  follow_mouse = 1
  float_switch_override_focus = false
  }
