# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D6D6D6
background         #201A16
cursor             #401B15

active_tab_foreground     #201A16
active_tab_background     #D6D6D6
inactive_tab_foreground   #D6D6D6
inactive_tab_background   #201A16

active_border_color   #D6D6D6
inactive_border_color #201A16
bell_border_color     #A62E1A

color0      #A5A5A4
color1		#A62E1A
color2		#733020
color3		#2A2526
color4		#351513
color5		#151414
color6		#121110
color7		#631B10
color8		#9B2B18
color9		#DD3D23
color10		#9A402A
color11		#373133
color12		#471C19
color13		#1C1B1A
color14		#181715
color15		#E69688
