# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D1D2D2
background         #0C1218
cursor             #25282A

active_tab_foreground     #0C1218
active_tab_background     #D1D2D2
inactive_tab_foreground   #D1D2D2
inactive_tab_background   #0C1218

active_border_color   #D1D2D2
inactive_border_color #0C1218
bell_border_color     #656667

color0      #9D9E9F
color1		#656667
color2		#565B5D
color3		#51565A
color4		#101416
color5		#0B0E11
color6		#0A0D11
color7		#3D3D3E
color8		#5E6061
color9		#87898A
color10		#73797B
color11		#6C7378
color12		#161B1E
color13		#0E1217
color14		#0E1216
color15		#BABBBC
